# 프로젝트 이름
spring.application.name=spring-ai-project

# 서버 포트
server.port=8080

# 터미널 컬러 출력
spring.output.ansi.enabled=ALWAYS

# 로깅
logging.pattern.console=%clr(%-5level){green} %clr(%logger.%M\\(\\)){cyan}: %msg%n

# 파일 업로드
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# 정적 리소스 캐시 사용 안함
spring.web.resources.chain.cache=false